# Generated by Django 2.1.7 on 2019-02-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripleJ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerequest',
            name='directory',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
